services:
  # JMS (de)serialze format: "atol_client".
  # $someValue <-> '"some_value"'.
  atol_client.serializer.visitor.deserialize.atol_client:
    class: JMS\Serializer\JsonDeserializationVisitor
    arguments: ['@atol_client.serializer.naming']
    tags: [{ name: 'jms_serializer.deserialization_visitor', format: 'atol_client' }]

  atol_client.serializer.visitor.serialize.atol_client:
    class: JMS\Serializer\JsonSerializationVisitor
    arguments: ['@atol_client.serializer.naming']
    tags: [{ name: 'jms_serializer.serialization_visitor', format: 'atol_client' }]

  # (De)serialization object <-> array.
  atol_client.serializer.visitor.serialize.array:
    class: JMS\Serializer\JsonSerializationVisitor
    arguments: ['@atol_client.serializer.naming']
    tags: [{ name: 'jms_serializer.serialization_visitor', format: 'atol_client' }]

  atol_client.serializer.visitor.deserialize.array:
    class: JMS\Serializer\JsonDeserializationVisitor
    arguments: ['@atol_client.serializer.naming']
    tags: [{ name: 'jms_serializer.deserialization_visitor', format: 'atol_client' }]

  atol_client.validator.attributes:
    class: Lamoda\AtolClient\V3\Validator\EmailOrPhoneValidator
    tags: [{ name: validator.constraint_validator }]

  # $someValue <-> 'some_value':
  atol_client.serializer.naming:
      class: "%jms_serializer.serialized_name_annotation_strategy.class%"
      arguments: ["@jms_serializer.camel_case_naming_strategy"]

  # Converts request and response from and to json.
  atol_client.object_converter:
    class: Lamoda\AtolClient\Converter\ObjectConverter
    arguments:
        - '@jms_serializer.serializer'
        - '@validator'

  # Serialization helpers
  atol_client.serializer.handlers.enum:
    class: Lamoda\AtolClient\Serializer\Handler\EnumHandler
    tags: [{ name: 'jms_serializer.subscribing_handler' }]

  atol_client.serializer.handlers.extended_date:
    class: Lamoda\AtolClient\Serializer\Handler\ExtendedDateHandler
    tags: [{ name: 'jms_serializer.subscribing_handler' }]

